create or alter procedure bronze.load_bronze as
begin
	declare @start_time datetime , @end_time datetime, @batch_start_time datetime, @batch_end_time datetime;
	begin try
		set @batch_start_time = getdate();
		print'=========================================';
		print'loading bronze layer';
		print'=========================================';

		print'-----------------------------------------';
		print'Loading CRM Tables';
		print'-----------------------------------------';

		----crm_cust_info
		set @start_time = getdate();
		print'>> Truncating Table:bronze.crm_cust_info'
		truncate table bronze.crm_cust_info;

		print'>> Inserting Data Into:bronze.crm_cust_info'
		bulk insert bronze.crm_cust_info
		from'C:\Users\Anish\Downloads\sql-data-warehouse-project\sql-data-warehouse-project\datasets\source_crm\cust_info.csv' 
		with(
			firstrow=2,
			fieldterminator=',',
			tablock
		);
		set @end_time = getdate();
		print'>>Load Duration:'+cast(datediff(second,@start_time, @end_time) as nvarchar)+'seconds';
		print'---------------------------------------------------------------------------------------------'

		----crm_prd_info
		set @start_time = getdate();
		print'>> Truncating Table:bronze.crm_prd_info'
		truncate table bronze.crm_prd_info;
	
		print'>> Inserting Data Into:bronze.crm_prd_info'
		bulk insert bronze.crm_prd_info
		from'C:\Users\Anish\Downloads\sql-data-warehouse-project\sql-data-warehouse-project\datasets\source_crm\prd_info.csv' 
		with(
			firstrow=2,
			fieldterminator=',',
			tablock
		);
		set @end_time = getdate();
		print'>>Load Duration:'+cast(datediff(second,@start_time, @end_time) as nvarchar)+'seconds';
		print'---------------------------------------------------------------------------------------------'

		----sales_details
		set @start_time = getdate();
		print'>> Truncating Table:bronze.crm_sales_details'
		truncate table bronze.crm_sales_details;
	
		print'>> Inserting Data Into:bronze.crm_sales_details'
		bulk insert bronze.crm_sales_details
		from'C:\Users\Anish\Downloads\sql-data-warehouse-project\sql-data-warehouse-project\datasets\source_crm\sales_details.csv' 
		with(
			firstrow=2,
			fieldterminator=',',
			tablock
		);
		set @end_time = getdate();
		print'>>Load Duration:'+cast(datediff(second,@start_time, @end_time) as nvarchar)+'seconds';
		print'---------------------------------------------------------------------------------------------'

		print'-----------------------------------------';
		print'Loading ERP Tables';
		print'-----------------------------------------';

		----erp_cust_az12
		set @start_time = getdate();
		print'>> Truncating Table:bronze.erp_cust_az12'
		truncate table bronze.erp_cust_az12;

		print'>> Inserting Data Into:bronze.erp_cust_az12'
		bulk insert bronze.erp_cust_az12
		from'C:\Users\Anish\Downloads\sql-data-warehouse-project\sql-data-warehouse-project\datasets\source_erp\cust_az12.csv' 
		with(
			firstrow=2,
			fieldterminator=',',
			tablock
		);
		set @end_time = getdate();
		print'>>Load Duration:'+cast(datediff(second,@start_time, @end_time) as nvarchar)+'seconds';
		print'---------------------------------------------------------------------------------------------'

		----erp_px_cat_g1v2
		set @start_time = getdate();
		print'>> Truncating Table:bronze.erp_px_cat_g1v2'
		truncate table bronze.erp_px_cat_g1v2;

		print'>> Inserting Data Into:bronze.erp_px_cat_g1v2'
		bulk insert bronze.erp_px_cat_g1v2
		from'C:\Users\Anish\Downloads\sql-data-warehouse-project\sql-data-warehouse-project\datasets\source_erp\px_cat_g1v2.csv' 
		with(
			firstrow=2,
			fieldterminator=',',
			tablock
		);
		set @end_time = getdate();
		print'>>Load Duration:'+cast(datediff(second,@start_time, @end_time) as nvarchar)+'seconds';
		print'---------------------------------------------------------------------------------------------'

		----erp_loc_a101
		set @start_time = getdate();
		print'>> Truncating Table: bronze.erp_loc_a101'
		truncate table bronze.erp_loc_a101;

		print'>> Inserting Data Into: bronze.erp_loc_a101'
		bulk insert bronze.erp_loc_a101
		from'C:\Users\Anish\Downloads\sql-data-warehouse-project\sql-data-warehouse-project\datasets\source_erp\loc_a101.csv' 
		with(
			firstrow=2,
			fieldterminator=',',
			tablock
		);
		set @end_time = getdate();
		print'>>Load Duration:'+cast(datediff(second,@start_time, @end_time) as nvarchar)+'seconds';
		print'---------------------------------------------------------------------------------------------'

		set @batch_end_time = getdate();
		print'==============================================================================='
		print'Loading Bronze Layer is completed';
		print'>>Total Load Duration:'+cast(datediff(second,@batch_start_time, @batch_end_time) as nvarchar)+'seconds';
		print'==============================================================================='
	end try
	begin catch
		print'=========================================';
		print'ERROR OCCURED DURING LOADING BRONZE LAYER';
		print'ERROR MESSAGE' + error_message();
		print'ERROR MESSAGE' + cast(error_number() as nvarchar);
		print'ERROR MESSAGE' + cast(error_state() as nvarchar);
		print'=========================================';
	end catch
end
